/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proyecto_com_lamemp3_Encoder */

#ifndef _Included_proyecto_com_lamemp3_Encoder
#define _Included_proyecto_com_lamemp3_Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     proyecto_com_lamemp3_Encoder
 * Method:    init
 * Signature: (IIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_proyecto_com_lamemp3_Encoder_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     proyecto_com_lamemp3_Encoder
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_proyecto_com_lamemp3_Encoder_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     proyecto_com_lamemp3_Encoder
 * Method:    encodeBufferInterleaved
 * Signature: ([SI[B)I
 */
JNIEXPORT jint JNICALL Java_proyecto_com_lamemp3_Encoder_encodeBufferInterleaved
  (JNIEnv *, jclass, jshortArray, jint, jbyteArray);

/*
 * Class:     proyecto_com_lamemp3_Encoder
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_proyecto_com_lamemp3_Encoder_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     proyecto_com_lamemp3_Encoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_proyecto_com_lamemp3_Encoder_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
